"""Add table visit_logs

Revision ID: 713cd9b53737
Revises: 951435f69c8c
Create Date: 2025-06-03 22:32:40.871481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713cd9b53737'
down_revision = '951435f69c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_visit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visit_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_logs')
    # ### end Alembic commands ###
